### ISSUE TITLE
Convert as much as possible from Hammerspoon to Karabiner-Elements

### ISSUE THREAD

**Issue by cdzombak** [cdzombak/dotfiles#10]
Now that Karabiner-Elements is a bit more mature, I want to try to move as much as I can from Hammerspoon into Karabiner.

Relevant:

https://pqrs.org/osx/karabiner/

How to switch the Case? · Issue #64 · jasonrudolph/keyboard
https://github.com/jasonrudolph/keyboard/issues/64

Bug when typing "s"/"d" with another character in rapid succession · Issue #40 · jasonrudolph/keyboard
https://github.com/jasonrudolph/keyboard/issues/40#issuecomment-469435330

Move SuperDuper mode to Karabiner-elements by narze · Pull Request #61 · jasonrudolph/keyboard
https://github.com/jasonrudolph/keyboard/pull/61

**Comment by njm2112** [comment]
Wondering if you found a working implementation for:

> How to switch the Case? · Issue #64 · jasonrudolph/keyboard
> jasonrudolph/keyboard#64

Using [goku](https://github.com/yqrashawn/GokuRakuJoudo), I tried implementing ESC to toggle a "capslock" mode by setting variable `"capslock" 1` and then, when in capslock mode, having each a-z keypress trigger !Sa-z. Unfortunately I can't figure out how to make the toggle happen (e.g. by pressing ESC again)--I can only get it to be on or off, but not switch between the two. Have you had any luck?

**Comment by narze** [comment]
@cdzombak If you still interested in SD mode, here's my Goku config which generates karabiner config file within Jason's repo.

https://github.com/narze/dotfiles/blob/master/etc/karabiner.edn#L62

Please note that I've been using this mode for so many years and I tweaked it a bit with more keys.

**Comment by cdzombak** [comment]
Background info from https://github.com/jasonrudolph/keyboard/issues/71#issuecomment-674560512 :

> It's possible to entirely remove the dependency on Karabiner-Elements, but in my experience, doing so has always involved some UX compromises.
> 
> Back in 2018, [pqrs-org/Karabiner-Elements#545](https://github.com/pqrs-org/Karabiner-Elements/issues/545) led me to remove the dependency on Karabiner-Elements and implement everything with Hammerspoon, and I shipped that change in [jasonrudolph/keyboard v4.0.0](https://github.com/jasonrudolph/keyboard/releases/tag/v4.0.0).
> 
> That worked, but I found the UX of that particular implementation to be inferior as described in #38. (Perhaps there's an alternative Hammerspoon-based implementation that would provide UX comparable to the Karabiner-Elements implementation, but I'm not aware of such an implementation.) So once [pqrs-org/Karabiner-Elements#545](https://github.com/pqrs-org/Karabiner-Elements/issues/545) was resolved, #38 reinstated the use of Karabiner-Elements.
> 
> The problems described in #40, #59, and #60 were also side effects of removing the dependency on Karabiner-Elements. #61 resolved those issues by porting (S)uper (D)uper Mode from Hammerspoon to Karabiner-Elements.
> 
> With that in mind, I will likely postpone my personal upgrade to Big Sur until https://github.com/pqrs-org/Karabiner-DriverKit-VirtualHIDDevice is capable of supporting all the existing functionality in this repository.
> 
> I hope that helps.
