### ISSUE TITLE
iCloud Drive path changes in macOS Catalina/Big Sur

### ISSUE THREAD

**Issue by cdzombak** [cdzombak/dotfiles#20]
New path is `~/Library/CloudStorage/iCloudDrive`

Setup script should migrate old shortcuts/links in `~`; see https://github.com/cdzombak/dotfiles/blob/master/macos-homedir.sh

https://eclecticlight.co/2019/08/21/its-time-to-test-your-scripts-against-catalinas-path-changes/

**Comment by andrewsardone** [comment]
This is good to know. As I'm still on Mojave, I wasn't aware there was a change.

**Comment by cdzombak** [comment]
Per a friend on Big Sur, it looks like this change was either temporary, a prerelease glitch, or only on Catalina:

```
file "$HOME/Library/Mobile Documents/com~apple~CloudDocs"
/Users/XXXX/Library/Mobile Documents/com~apple~CloudDocs: directory
$ ls -lh "$HOME/Library/Mobile Documents/com~apple~CloudDocs"
total 1234
drwxr-xr-x@ 3 XXXX  staff    96B Jun 22  2019 Desktop
drwxr-xr-x@ 4 XXXX  staff   128B May 16  2019 Documents
drwxr-xr-x@ 4 XXXX  staff   128B Feb 13 09:30 Downloads
```

So no action is needed right now. I did push a version of the homedir creation script which would create links to the new location — but not migrate existing links after a system upgrade — to the branch [`cdz/catalina-icloud-drive-path`](https://github.com/cdzombak/dotfiles/blob/cdz/catalina-icloud-drive-path/macos-homedir.sh), in case I need it in the future.
